### ISSUE TITLE
ExtendedSplashScreen

### ISSUE THREAD

**Issue by hippieZhou** [bsonnino/CustomerCrud#1]
Execute me ? I want to known to that how can I add a ExtendedSplashScreen in this template by right way ?

**Comment by bsonnino** [comment]
I don't see why you can't use this procedure http://www.c-sharpcorner.com/UploadFile/020f8f/universal-windows-platform-and-extended-splash-screen/
The project created with the WTS has basically the same structure of that project

**Comment by hippieZhou** [comment]
ok.thank you for your help.
